Nickbgor/footer
zhashkevych/courses-frontend pull request #12
Opened 2021-04-05 08:52 UTC by NickBGor

2021-04-07 06:11 UTC, zhashkevych commented on src/components/Footer/Footer.js
> +  { link: '', name: 'ФЛП: Иванов Иван Иванович' },
В этот блок также стоит добавить адрес, как в https://layb.io/

Значения для имени, рег. номера, адреса и email должны подставляться динамически, получить их можно тут
https://api-stage-creatly.zhashkevych.com/swagger/index.html#/school-settings/get_settings

2021-04-08 20:06 UTC, eugenakin requested changes

2021-04-08 20:06 UTC, eugenakin commented on src/components/Header/styles/HeaderStyled.js
> +
пустая строка

2021-04-08 20:06 UTC, eugenakin commented on src/components/Footer/styles/FooterStyled.js
> +
не надо пустых строк

2021-04-08 20:06 UTC, eugenakin commented on src/components/Footer/styles/FooterStyled.js
> +  > span {
не очень люблю стилизацию по тегах, тег может поменяться и всё сломается :)
если это текст то ты можешь использовать свой компонент как селектор:
`${BodyItem} { ... }`

2021-04-08 20:06 UTC, eugenakin commented on src/components/Footer/Footer.js
> +import { FondayLogoCard } from 'COMPONENTS/Footer/components/FondayLogoCard';
лучше уже вынести в компоненты, а то только ради этого дополнительную вложенность делать не ок, такое имеет смысл делать в каких-то супер сложных компонентах, что бы было проще работать с ними.
или даже не дробить, если он только тут юзается.

2021-04-09 03:24 UTC, NickBGor commented on src/pages/Service/Service.js
> +const Service = () => <h1>Страница условий предоставления услуг</h1>;
Ты же вроде просил страницы дефолтно экспортировать.

2021-04-09 19:51 UTC, eugenakin commented on src/pages/Service/Service.js
> +const Service = () => <h1>Страница условий предоставления услуг</h1>;
да, но ты же всё равно ре-эекспорт делаешь в индексе, так проще экспортнуть оттуда

2021-04-12 08:50 UTC, eugenakin approved these changes

2021-04-12 08:50 UTC, merged