Nickbgor/notifications
zhashkevych/courses-frontend pull request #18
Opened 2021-04-20 04:50 UTC by NickBGor

2021-04-20 16:48 UTC, eugenakin requested changes

2021-04-20 16:48 UTC, eugenakin commented on src/components/Notifications/Notifications.js
> +  const [open, setOpen] = useState(false);
isOpen

2021-04-20 16:48 UTC, eugenakin commented on src/components/Notifications/Notifications.js
> +  const successMsg = useSelector(({ notifications }) => notifications.success);
можно сразу два вытянуть:
`const { error, success } = useSelector(({ notifications }) => notifications);`

2021-04-20 16:48 UTC, eugenakin commented on src/components/Notifications/Notifications.js
> +  };
enter

2021-04-20 16:48 UTC, eugenakin commented on src/pages/Home/Home.js
>    const isLoading = useSelector(({ courses }) => courses.isLoading);
можно так
`const { isLoading } = useSelector(({ courses }) => courses);`

2021-04-20 16:48 UTC, eugenakin commented on src/pages/Home/Home.js
>    }, [fetchCourses]);
а как fetchCourses может поменяться?

2021-04-20 16:48 UTC, eugenakin commented on src/store/notifications/index.js
> +  name: 'app',
давай так и назвем: notifications

2021-04-20 16:48 UTC, eugenakin commented on src/store/notifications/index.js
> +      ...state,
с redux-toolkit тебе не обязательно всегда копировать стейт, там под капотом [immerjs](https://github.com/immerjs/immer). ты можешь писать проще, как будто мутируешь:
```
setErrorsMsg: (state, { payload: { message }) => {
    state.error = message;
};
```

2021-04-20 16:48 UTC, eugenakin commented on src/store/notifications/index.js
> +    setErrorsMsg: (state, { payload }) => ({
setErrorMessage, без множественного числа.
или там сразу пару можно сетить?

2021-04-20 16:48 UTC, eugenakin commented on src/utils/dispatchErrorMsg.js
> +export const dispatchErrorMsg = (dispatch, error) => {
а просто заменять не вариант там?
что бы не делать этой лишней обёртки

2021-04-20 16:48 UTC, eugenakin commented on src/components/Notifications/Notifications.js
> +    if (reason === 'clickaway') {
можно в строчку такое
`if (reason === 'clickaway') return;`

2021-04-21 04:38 UTC, NickBGor commented on src/store/notifications/index.js
> +    setErrorsMsg: (state, { payload }) => ({
Пока что одна ошибка на один ответ может быть, судя по свагеру

2021-04-21 04:40 UTC, NickBGor commented on src/utils/dispatchErrorMsg.js
> +export const dispatchErrorMsg = (dispatch, error) => {
Я хотел сделать обертку что бы каждый раз не забывать подчищать текущие ошибки и сетить новые. Если без обертки это нужно будет не забывать делать так где вызываешь action

2021-04-21 07:40 UTC, eugenakin requested changes

2021-04-21 07:40 UTC, eugenakin commented on src/api/endpoints.js
> +    getAll: `${API_URL}/courses2  `,
2 лишнее ;)

2021-04-21 07:40 UTC, eugenakin commented on src/components/Routes/PrivateRoute.js
> +        if ((!token && !refresh) || (!adminToken && !adminRefresh)) {
нужно назад вернуть

2021-04-21 11:09 UTC, eugenakin approved these changes

2021-04-21 11:09 UTC, merged