Добавлены карточки курсов на главную страницу
zhashkevych/courses-frontend pull request #5
Opened 2021-03-22 16:24 UTC by NickBGor

2021-03-22 17:09 UTC, zhashkevych approved these changes

2021-03-23 19:47 UTC, JeniaEnakin requested changes
В общем супер, но есть моменты ;)

2021-03-23 19:47 UTC, JeniaEnakin commented on src/components/CourseCart/index.js
> +export const CourseCart = ({ name, description, imageUrl }) => (
Cart это по сути корзина с английского, поменяй все упоминания на Card ;)

2021-03-23 19:47 UTC, JeniaEnakin commented on src/components/CourseCart/index.js
> +  name: 'Тут должно быть имя курса...',
не думаю что есть надобность задавать такие дефолтные пропсы, тут либо null, либо сделай их isRequired

2021-03-23 19:47 UTC, JeniaEnakin commented on src/components/CourseCart/styles/CourseCartStyle.js
> +
удали пустую строку

2021-03-23 19:47 UTC, JeniaEnakin commented on src/pages/Home/index.js
> +import { Content, HomeStyled, PageTitle } from 'PAGES/Home/styles/HomeStyled';
когда ты в папке с тем что тебя надо то используй просто относительный путь, в данном случае './styles/HomeStyled'

2021-03-23 19:47 UTC, JeniaEnakin commented on src/pages/RootRouter.js
> +import { HomePage } from 'PAGES/Home';
делай дефолт экспорт страниц, а не именований, потому что в будущем можно будет подрубить [саспенс](https://uk.reactjs.org/docs/concurrent-mode-suspense.html) для них, когда он станет стабильной фичей

2021-03-23 19:47 UTC, JeniaEnakin commented on src/store/home/index.js
> +  name: 'home',
думаю тут можно назвать просто courses, не надо привязываться к страницам, тут больше про данные, которые мы храним

2021-03-23 19:47 UTC, JeniaEnakin commented on src/pages/Home/index.js
> +export const HomePage = () => {
думаю нет смыслы добавлять к названию Page, и так понятно что это страница, а так везде прийдется писать ;)

2021-03-24 07:12 UTC, zhashkevych approved these changes

2021-03-24 09:41 UTC, eugenakin approved these changes

2021-03-24 09:42 UTC, merged