Nickbgor/course page
zhashkevych/courses-frontend pull request #8
Opened 2021-03-28 04:59 UTC by NickBGor

2021-03-29 06:43 UTC, zhashkevych approved these changes

2021-03-30 20:58 UTC, eugenakin requested changes

2021-03-30 20:58 UTC, eugenakin commented on src/api/endpoints.js
> +    getOne: (id) => `${API_URL}/courses/${id}`,
думаю лучше будет назвать getById

2021-03-30 20:58 UTC, eugenakin commented on src/components/CourseCard/index.js
> +      <Link to={`course/${id}`}>
это лучше в constants/routes добавить, что б без хардкода

2021-03-30 20:58 UTC, eugenakin commented on src/components/CourseModule/index.js
> +  const [openModule, setOpenModule] = useState(false);
хорошей практикой считается начинать название переменных, которые описывают какое-то состояние со слов is, has, should и т.д.
в этом случае:
`const [isModuleOpen, setModuleOpen] = useState(false);`

2021-03-30 20:58 UTC, eugenakin commented on src/components/CourseModule/index.js
> +        ? lessons.map((lesson) => (
если тебе не надо else условие, то можно просто сделать через && вместо тернарника с else null

2021-03-30 20:58 UTC, eugenakin commented on src/components/CourseModule/styles/CourseModuleStyles.js
> +    transform: ${({ open }) => (open ? 'rotate(180deg)' : '')};
isOpen

2021-03-30 20:58 UTC, eugenakin commented on src/pages/Course/index.js
> +  const checkModulesBlock = () => !!(modules && modules.length);
функцию тоже можно называть с is, has если она чисто для того что бы вернуть булеан

2021-03-30 20:58 UTC, eugenakin commented on src/pages/Course/index.js
> +  const checkModulesBlock = () => !!(modules && modules.length);
`!!(modules && modules.length)`
можно поменять, используя optional chaining, на:
`!!modules?.length`

2021-03-30 20:58 UTC, eugenakin commented on src/pages/Course/index.js
> +              <Link to={`/module/${checkModulesBlock() ? modules[0].id : ''}`}>
роут в константы, если там нет

2021-03-30 20:58 UTC, eugenakin commented on src/pages/Course/index.js
> +            ) : null}
тут тоже можно написать через && и else убрать

2021-03-30 20:58 UTC, eugenakin commented on src/store/courses/index.js
> +export const fetchCourses = createAsyncThunk('courses/fetchCourses', () => apiGetAllCourses().then((res) => res.data));
всё таки с промисами варик больше зашел?)

2021-03-30 20:58 UTC, eugenakin commented on src/pages/Course/index.js
> +    return dispatch(clearCourse());
ты уверен что так работает очистка? перепроверь
потому что useEffect должен возвращать функцию которая будет вызвана, а не сам вызов
мне кажется тут надо обернуть в анонимную стрелку

2021-03-31 04:52 UTC, NickBGor commented on src/store/courses/index.js
> +export const fetchCourses = createAsyncThunk('courses/fetchCourses', () => apiGetAllCourses().then((res) => res.data));
Решил просто уже в одной стилистике писать.
Нет особо времени отрефакторить все, поэтому на мой взгляд лучше что бы было в одном стиле. В других логических кусках приложения буду писать async/await.

2021-04-01 21:06 UTC, eugenakin approved these changes

2021-04-01 21:06 UTC, merged